# Generated by Django 4.2 on 2023-06-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(verbose_name='Url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.category', verbose_name='Нкатегория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='catergory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='finish',
            field=models.DateTimeField(null=True, verbose_name='Завершить'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=2, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Начать'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
