# Generated by Django 4.2.2 on 2023-06-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_alter_order_category_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfcategory', to='freelance.category'),
        ),
    ]
