# Generated by Django 4.2.3 on 2023-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание каткгории'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
